name: Mend SCA with Quality Gate
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 'pypy3.9'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Mend Unified Agent Scan
      env:
        WS_APIKEY: ${{secrets.SCA_APIKEY}}
        WS_USERKEY: ${{secrets.SCA_USERKEY}}
        WS_WSS_URL: https://saas-eu.mend.io/agent
        WS_PRODUCTNAME: GHActions_${{github.event.repository.name}}
        WS_PROJECTNAME: ${{github.ref}}
        WS_RESOLVEALLDEPENDENCIES: false
        WS_PYTHOn_RESOLVEDEPENDENCIES: true
        WS_FILESYSTEMSCAN: true
        WS_GENERATEPROJECTDETAILSJSON: true
        WS_CHECKPOLICIES: true
      run: |
        curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
        echo Unified Agent downloaded successfully
        java -jar wss-unified-agent.jar